name: Send Failure  Success Email

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/alert.yml

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Alert.yml Updated!"
          to: msstyles141@gmail.com
          from: GitHub Actions
          body: |
            The `alert.yml` workflow file has been updated on branch `main`.
            👉 View the commit: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
