name: Send Failure or Success Email

on:
  workflow_run:
    workflows: ["Python CI with Logging"]
    types:
      - completed
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Check and send appropriate email
        if: always()  # Always run this step after workflow completion
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ${{ github.event.workflow_run.conclusion == 'failure' && 'Python CI Failed' || 'Python CI Passed' }}
          to: msstyles141@gmail.com
          from: GitHub Actions
          body: |
            The Python CI workflow has completed with status: ${{ github.event.workflow_run.conclusion }}.
            View the workflow logs here: ${{ github.event.workflow_run.html_url }}
